name: "CI Basics"

on:
    push: ~
    workflow_dispatch: ~

jobs:
    hello:
        name: "Hello World War"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Say hello"
                run: echo "Hello World War"

    hello2:
        name: "Hello World War 2"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Say hello again"
                run: |
                    echo "Hello World War 2"
                    echo "Hello World War 3"
            -   name: "Say goodbye"
                run: echo "Goodbye World War"

    hello3:
        needs: [ "hello", "hello2" ]
        name: "Hello World Peace"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Say hello again"
                run: echo "Hello World Peace"