name: "CI"

on:
    push:
        paths-ignore: "./ci-basics.yml"
    workflow_dispatch: ~

jobs:
    deps:
        name: "Install dependencies"
        runs-on: "ubuntu-latest"
        steps:
            -   uses: actions/checkout@v2
            -   name: "Install php and composer dependencies"
                run: |
                    sudo apt-get update
                    sudo apt-get install -y php-cli php-xml composer
                    composer install